## ***Initials***

In [1]:
import pandas as pd

## ***Load the Data***

In [3]:
df1 = pd.read_csv("C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\3. Base Datasets\\2. Data - Municipal Communities\\1. Demographic Data\\Extracted CSV Files\\ELSTAT-demographic.csv")
df2 = pd.read_csv("C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\3. Base Datasets\\2. Data - Municipal Communities\\2. Economic Data\\Extracted CSV Files\\ELSTAT-economic.csv")

In [4]:
print(df1.shape)
df1.head()

(76, 32)

,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ,ΔΗΜΟΣ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ,ΔΗΜΟΤΙΚΗ ΚΟΙΝΟΤΗΤΑ,Population,0-4,5-9,10-14,15-19,25-29,...,high_school,lower_secondary,primary_education,no_formal_education,not_classified,Άγαμοι,Έγγαμοι,Χήροι,Διαζευγμένοι,20-24
0,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΒΟΛΟΥ,Δημοτική Κοινότητα Βόλου,85806,3204,3638,4315,5086,4174,...,25000,10353,12509,6950,3761,34601,39731,6940,4530,5412
1,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΓΡΙΑΣ,Δημοτική Κοινότητα Αγριάς,4926,183,247,263,277,203,...,1302,717,994,486,221,1762,2548,392,227,233
2,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΓΡΙΑΣ,Δημοτική Κοινότητα Δρακείας,369,11,14,22,16,21,...,74,47,131,60,12,129,169,51,12,15
3,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΙΣΩΝΙΑΣ,Δημοτική Κοινότητα Διμηνίου,2101,102,97,112,127,119,...,534,340,483,253,122,817,1052,163,72,106
4,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΙΣΩΝΙΑΣ,Δημοτική Κοινότητα Σέσκλου,899,36,51,72,40,47,...,208,142,224,149,42,356,466,58,21,38

In [5]:
print(df2.shape)
df2.head()

(76, 12)

,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ,ΔΗΜΟΣ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ,ΔΗΜΟΤΙΚΗ ΚΟΙΝΟΤΗΤΑ,Σύνολο,Οικονομικά ενεργοί,Απασχολούμενοι,Πρωτογενής,Δευτερογενής,Τριτογενής,Άνεργοι,Οικονομικά μη ενεργοί
0,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΒΟΛΟΥ,Δημοτική Κοινότητα Βόλου,85806,35938,30389,950,5062,24377,5551,49865
1,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΓΡΙΑΣ,Δημοτική Κοινότητα Αγριάς,4926,1948,1642,134,306,1201,303,2981
2,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΓΡΙΑΣ,Δημοτική Κοινότητα Δρακείας,369,139,121,55,10,56,20,227
3,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΙΣΩΝΙΑΣ,Δημοτική Κοινότητα Διμηνίου,2101,909,706,82,167,456,201,1194
4,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΙΣΩΝΙΑΣ,Δημοτική Κοινότητα Σέσκλου,899,345,302,43,109,150,45,552

## ***Merge the Datasets***

In [6]:
common_cols = ['ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ', 'ΔΗΜΟΣ', 'ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ', 'ΔΗΜΟΤΙΚΗ ΚΟΙΝΟΤΗΤΑ']

In [8]:
merged_df = pd.merge(df1, df2, on=common_cols, how='inner')

In [9]:
print(merged_df.shape)
merged_df.head()

(76, 40)

,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ,ΔΗΜΟΣ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ,ΔΗΜΟΤΙΚΗ ΚΟΙΝΟΤΗΤΑ,Population,0-4,5-9,10-14,15-19,25-29,...,Διαζευγμένοι,20-24,Σύνολο,Οικονομικά ενεργοί,Απασχολούμενοι,Πρωτογενής,Δευτερογενής,Τριτογενής,Άνεργοι,Οικονομικά μη ενεργοί
0,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΒΟΛΟΥ,Δημοτική Κοινότητα Βόλου,85806,3204,3638,4315,5086,4174,...,4530,5412,85806,35938,30389,950,5062,24377,5551,49865
1,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΓΡΙΑΣ,Δημοτική Κοινότητα Αγριάς,4926,183,247,263,277,203,...,227,233,4926,1948,1642,134,306,1201,303,2981
2,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΓΡΙΑΣ,Δημοτική Κοινότητα Δρακείας,369,11,14,22,16,21,...,12,15,369,139,121,55,10,56,20,227
3,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΙΣΩΝΙΑΣ,Δημοτική Κοινότητα Διμηνίου,2101,102,97,112,127,119,...,72,106,2101,909,706,82,167,456,201,1194
4,ΠΕΡΙΦΕΡΕΙΑΚΗ ΕΝΟΤΗΤΑ ΜΑΓΝΗΣΙΑΣ,ΔΗΜΟΣ ΒΟΛΟΥ,ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΙΣΩΝΙΑΣ,Δημοτική Κοινότητα Σέσκλου,899,36,51,72,40,47,...,21,38,899,345,302,43,109,150,45,552

## ***Save the Data***

In [ ]:
merged_df.to_csv("C:\\Users\\Giorgos\\Desktop\\HMMY\\10ο Εξάμηνο\\Διπλωματική\\3. Base Datasets\\2. Data - Municipal Communities\\3. Merging the ELSTAT Data\\Extracted CSV Files\\ELSTAT-demographic-economic.csv", index=False)